### PR TITLE
Rebrand to Openverse

### LINKED ISSUE #2: Rebrand the extension for Openverse
The rebranding of CC Search to Openverse should also reflect in the extension. This includes
- changing the name
- updating static assets such as logos
- updating documentation
- new UI styles

Forked from WordPress/openverse#37

### PR DESCRIPTION
**Pull request by dhruvkb**
Partially addresses #2 

**Description**
This PR rebrands the extension to Openverse. This includes text and static assets but **"not"** UI and visual styles.

**Checklist:**
- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `main` branch of the repository.
- [x] My commit messages follow [best practices][best_practices].
- [ ] I added tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by zackkrida** [comment]
Wanted to test this but having an issue with `node-gyp`. Classic! I will try again Monday—thanks @dhruvkb !

**Comment by dhruvkb** [comment]
I think I built this on Node 14 and didn't get any `node-gyp` errors. Could you try that when you have some time?

**Review by zackkrida — APPROVED** [review]
Looks good to me, I just think the logo is 5-10 pixels too big from a design perspective. LGTM though and fix after we redesign colors and layout.

**Comment by dhruvkb** [comment]
Yes @zackkrida, the design needs significant improvement. I suppose we should wait for @panchovm's new designs for the extension before investing effort into that.

**Comment by panchovm** [comment]
I think working on this after being done with audio integration mockups makes sense. It shouldn't imply a redesign in terms of IA and features but a style update.

**Comment by zackkrida** [comment]
Yes, just a re-skin with the new colors, fonts, and whitespace changes

**Pull request merged**
